sudo: false
language: node_js
node_js:
  - "10"
install:
  - npm install -g markdownlint-cli@git+https://github.com/VeselovAlex/markdownlint-cli.git#custom-rules
  - npm install
  - git clone https://github.com/axibase/atsd.git /tmp/atsd
  - git clone https://github.com/axibase/atsd-use-cases.git /tmp/atsd-use-cases
  - git clone https://github.com/axibase/axibase-collector.git /tmp/axibase-collector
  - wget -P /tmp/axibase-collector https://raw.githubusercontent.com/axibase/atsd/master/.markdownlint.json
script:
  - npm run test
after_script:
  - markdownlint -i . --config /tmp/atsd/.markdownlint.json -r "linting-rules/*" /tmp/atsd
  - markdownlint -i . --config /tmp/atsd-use-cases/.markdownlint.json -r "linting-rules/*" /tmp/atsd-use-cases
  - markdownlint -i . --config /tmp/axibase-collector/.markdownlint.json -r "linting-rules/*" /tmp/axibase-collector
cache:
  directories:
    - $(npm config get prefix)/lib/node_modules
notifications:
  webhooks: https://apps.axibase.com/api/v1/messages/wk-travis-ci/travis-ci?json.parse=payload&exclude=payload.id;payload.number;payload.config*;payload.repository*;payload.matrix*;payload.*commit*;payload.status_message;payload.result&include=payload.repository.name&command.message=payload.result_message
branches:
  only:
    - master
