sudo: false
language: node_js
node_js:
  - "10"
install:
  - npm install -g markdownlint-cli@git+https://github.com/VeselovAlex/markdownlint-cli.git#custom-rules
  - npm install
  - wget https://raw.githubusercontent.com/axibase/atsd/master/.markdownlint.json
  - git clone https://github.com/axibase/atsd.git /tmp/atsd
script:
  - npm run test
  - markdownlint -i . -r "linting-rules/*" /tmp/atsd
cache:
  directories:
    - $(npm config get prefix)/lib/node_modules
notifications:
  webhooks: https://apps.axibase.com/api/v1/messages/wk-travis-ci/travis-ci?json.parse=payload&exclude=payload.id;payload.number;payload.config*;payload.repository*;payload.matrix*;payload.*commit*;payload.status_message;payload.result&include=payload.repository.name&command.message=payload.result_message
branches:
  only:
    - master